version: "3.6"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    depends_on:
      - mysql-data
    networks:
      - mysql-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'zipster'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
  mysql-data:
    image: howarddeiner/zipster-mysql-data
    container_name: mysql-data
    volumes:
      - ./mysql-data:/datafolder
    restart: always
networks:
  mysql-net:
    driver: bridge