version: "3.6"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - mysql-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'zipster'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - zipster-mysql-data:/var/lib/mysql
    restart: always
volumes:
  zipster-mysql-data:
networks:
  mysql-net:
    driver: bridge