version: "3.6"
services:
  wiremock:
    image: rodolpheche/wiremock
    container_name: wiremock
    ports:
      - "9001:8080"
    volumes:
      - ./wiremock:/home/wiremock
    restart: always
  zipster:
    depends_on:
      - mysql
    image: howarddeiner/zipster-spark
    container_name: zipster
    ports:
      - "9002:9002"
    restart: always
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'zipster'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - zipster-mysql-data:/var/lib/mysql
    restart: always
volumes:
  zipster-mysql-data: