CREATE TABLE ZIPCODES
(
    ZIPCODE       INT,
    ZIPCODE_TYPE  VARCHAR(16),
    CITY          VARCHAR(32),
    STATE         VARCHAR(2),
    LOCATION_TYPE VARCHAR(16),
    LATITUDE      FLOAT,
    LONGITUDE     FLOAT,
    LOCATION      VARCHAR(64),
    DECOMISSIONED BOOLEAN
);
